### ISSUE TITLE
Social media icons on speaker view don't actually link to anything 

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#10]
On the speaker view, the various social media icons (Twitter, LinkedIn, etc) don't link to anything, nor do they show the urls / handles for the speaker, so don't provide much value.

**Comment by mdridley** [comment]
Do you have an example? They only show for people that have links in their profile for that type, and when you click on them, it opens that link. I just re-tested and still see it working.

**Comment by johnmwright** [comment]
It appears to be fixed in the 3.0.1 release. I was able to reproduce it on my iPad (which still had 3.0.0), the upgraded to 3.0.1 and the issue went away.
Thanks
~john

On Sun, Jul 3, 2016 at 11:18 AM -0500, "Matthew Ridley" notifications@github.com wrote:

Do you have an example? They only show for people that have links in their profile for that type, and when you click on them, it opens that link. I just re-tested and still see it working.

---

**Comment by mdridley** [comment]
Perfect, thanks!
