### ISSUE TITLE
"Postcard" feature crashed app

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#13]
I clicked the camera icon in the upper right corner of the Settings view, which took me to the Postcard feature. I picked the "Test Frame". On the following view, I first picked "use camera", agreed to give the app access to the camera, but thn cancelled the camera view. I then picked "from photo library", granted the app access to my photos, selected a photo, zoomed it in about 50% and clicked "save postcard". At this point, the app crashes. 

Note: I've tried to reproduce this and have been unable to do so.

**Comment by mdridley** [comment]
Oh shoot, should be disabled for all screens, must have gotten turned on for that page by accident. Still a work in progress. :)

**Comment by mdridley** [comment]
Fixed. Will be in 3.1.x
