### ISSUE TITLE
Favorites has different layout from Schedule

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#14]
(This is not a major issue - just something that was a little jarring visually)

The layout of session info (category and room in particular) is different on the Favorites screen than the Schedule screen. Specifically, on the favorites screen, the category and room are on a single line in orange, while the Schedule screen shows each on a seperate line, with the room in gray and the addition of the speaker name (which is missing from the favorites view) with an icon for each. 

![image](https://cloud.githubusercontent.com/assets/3373249/16985388/9375a21a-4e45-11e6-94e1-56dcd405725b.png)
![image](https://cloud.githubusercontent.com/assets/3373249/16985389/93869a34-4e45-11e6-87d7-1da8f0d52d91.png)

**Comment by mdridley** [comment]
We went back and forth on this one. Idea originally was to keep favorites slimmed down since you should know most of the information because you added it. However... we started adding stuff back to it now.

Right now swiping the individual item triggers remove... would you find it better to have the heart interaction here as well even though it was basically for remove only.

**Comment by johnmwright** [comment]
I'm a big fan of internal consistency. Meaning: if I interact with the UI one way on one screen, I expect that interaction will be the same on all screens.

So swiping left/right on the schedule will change the day - I expect that to be the same behavior on the other list screens too. Adding/removing favorites is done via hearts on the schedule and session details screens - I'd expect that to be how it's done everywhere.

That said, I could see _not_ having the heart icon on the favorites list and needing to click into the details screen to remove it as a favorite. But, honestly, as a user, I'd prefer to have the same layout on all three schedule screens (favorites, schedule, open spaces).

Having consistency means I don't have to think about how to interact with the app and instead focus on the content. If I have to figure out the UX on each screen, I'm gonna spend too much mental energy on stuff beyond the content - which is what I'm using that app for in the first place.

Thanks
~john

On Wed, Jul 20, 2016 at 8:03 AM -0500, "Matthew Ridley" <notifications@github.com<mailto:notifications@github.com>> wrote:

We went back and forth on this one. Idea originally was to keep favorites slimmed down since you should know most of the information because you added it. However... we started adding stuff back to it now.

Right now swiping the individual item triggers remove... would you find it better to have the heart interaction here as well even though it was basically for remove only.

##

**Comment by mdridley** [comment]
Targeting for 3.1.x

**Comment by mdridley** [comment]
Fixed in 3.1.0.1
