### ISSUE TITLE
Favorites error handling for no network

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#15]
(There are a few related issues listed in this ticker, so make sure to scroll past the screenshots to see the additional issues)
# Test scenario:

Open app and authenticate.  View schedule screen with session that is not a favorite. Put device into airplane mode to simulate network loss. Attempt to mark a session as a favorite.
# Issue 1: wrong error for adding favorite failure

The error message shown when the call to mark a session as a favorite shows text as if removing the favorite.

![image](https://cloud.githubusercontent.com/assets/3373249/16985877/ff498198-4e48-11e6-91a3-05fa2e2d3eec.png)
# Issue 2: no error for removing favorite failure

 When attempting to remove a favorite and there is a network failure, no error message is displayed. 
# Issue 3: incorrect state after failure

When a failure occurs changing the state of a favorite (either to add or remove favorite status), the app flips the favorite flag locally even though the network call failed. 

For example, if a session starts off not marked as a favorite and the user clicks the heart icon to add it as a favorite but the network call fails, the app still marks the session as a favorite locally (shows red heart).  Meanwhile, the website does not show it as a favorite and restarting the app again shows it as not a favorite.

The inverse scenario has the same issue, but with the added complication that not error is shown to the user (see issue 2 above).

**Comment by mdridley** [comment]
Will work through this one.

**Comment by mdridley** [comment]
Fixed in 3.0.4
