### ISSUE TITLE
Really long session title push room off screen space on schedule

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#16]
When on the schedule screen, if the session has a really long title (4 lines), it pushes the room off the visible area of the session's panel. (See first session in screenshot)

![image](https://cloud.githubusercontent.com/assets/3373249/16986074/4d57dc44-4e4a-11e6-92a1-feaae0bc9300.png)

**Comment by mdridley** [comment]
Good find. Will check layout to make sure it is resizing correctly.

**Comment by mdridley** [comment]
Fixed in 3.0.4
