### ISSUE TITLE
Long room names don't wrap on session details screen

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#17]
When a "room" name is really long, it doesn't wrap on the session details screen. (It does wrap on the schedule screen)

I think this only affects the That 5k sessions. 

![image](https://cloud.githubusercontent.com/assets/3373249/16986247/0de453a2-4e4b-11e6-9bd1-50ca29971702.png)

**Comment by mdridley** [comment]
Fixed in 3.0.4
