### ISSUE TITLE
Sponsors logo centered, name/links left justified

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#18]
The layout of the sponsors screen is a bit wonky with the logos centered but their name and social links left justified. I would suggest centering everything. 

![image](https://cloud.githubusercontent.com/assets/3373249/16986496/6a846164-4e4c-11e6-9b6e-9e525b0fbfce.png)

**Comment by mdridley** [comment]
Fixed in 3.0.4
