### ISSUE TITLE
Sign out doesn't clear favorites data

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#19]
After clicking the "sign out" button, the app doesn't clear my favorites data. I would suggest it send the user directly to the login screen after successful sign out.

**Comment by mdridley** [comment]
That is a good idea for interaction. I will check why favorites are not clearing properly, must be issue with dirty flag.

**Comment by mdridley** [comment]
Data was empty, but cached view was still showing behind alert. Cleared cache now if data is dirty.

Fixed in 3.0.4
