### ISSUE TITLE
When I update my profile in the app, cannot navigate back

### ISSUE THREAD

**Issue by kingofzeal** [ThatConference/mobile-ios#26]
As the title says, I cannot navigate around the app if I update my profile from within the app.

Steps to reproduce:

- Log into the app with an existing account
- Tap your name in the menu bar to open your profile
- Tap the edit button, and change the contents of a field (I had the issue with Title, but suspect it happens with any)
- Tap the Save button
- Dismiss the confirmation that your profile was updated
- Attempt to navigate 'Back' with the top left icon
- Nothing happens

Expected behavior:
I can navigate back to the non-editable profile page.

Force-killing the app appears the only way to get out of this state.

**Comment by mdridley** [comment]
Fixed in 4.1.4

**Comment by mcookWI** [comment]
Version 4.1.4 - verified that upon clicking OK on the "Successfully saved profile changes" message, you are taken back to the non-editable profile page.
