### ISSUE TITLE
Schedule View - Tapping favorite heart when not logged in does nothing

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-ios#28]
App version 4.1.3.0, running on an iPhone 7 Plus, iOS version 12.3.1:

When the user is not logged into the app, tapping the favorite heart does nothing. If the user is not logged in, I'd think the hearts would not appear, or possibly take them to the login screen.

**Comment by mdridley** [comment]
Fixed in 4.1.4

**Comment by mcookWI** [comment]
4.1.4 - User is taken to the login screen when tapping a heart when not signed in.
