### ISSUE TITLE
Edit Profile - Remove GooglePlus Profile URL field - G+ is no longer available

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/mobile-ios#30]
App Version 4.1.3.0

When in the screen to edit the user profile, the GooglePlus Profile URL field should be removed. Google+ is no longer available.

![IMG_3113](https://user-images.githubusercontent.com/5367626/61014007-e700af80-a34a-11e9-873c-0202788f9921.jpg)

**Comment by mdridley** [comment]
Fixed in 4.1.4

**Comment by mcookWI** [comment]
Verified that the field is gone in 4.1.4.
