### ISSUE TITLE
Schedule view heart not always updated when returning from session view

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#7]
Sometimes, when I'm in the session detail view and I favorite a session, then immediately jump back to the full schedule view, that session isn't showing as favorited (ie: the heart is still gray). If I go back into the session view and return to the schedule, the schedule then correctly shows the favorited heart.

**Comment by johnmwright** [comment]
found in v3.0.0.1

**Comment by mdridley** [comment]
Seems to be a timing issue. Will keep an eye on it. Might need to halt navigation while favoriting to make sure that the proper triggers for updates are occurring. Please let me know if you still see this in 3.0.3.1
