### ISSUE TITLE
Session name lays on top of track/room label in iPad landscape orientation

### ISSUE THREAD

**Issue by johnmwright** [ThatConference/mobile-ios#9]
On an iPad mini, when in landscape orientation, on the schedule view, the title text overlays on top of the track/room text. Not all sessions affected. 

![image](https://cloud.githubusercontent.com/assets/3373249/16471061/fd8bb792-3e1f-11e6-8c18-beb8fee754b8.png)
![image](https://cloud.githubusercontent.com/assets/3373249/16471059/fc3c4c80-3e1f-11e6-90a1-699b226538cf.png)

**Comment by johnmwright** [comment]
It's inconsistent, but I've noticed that If the view is first loaded while in landscape orientation, the titles wrap.  If I shift to portrait orientation, they redraw to extend out (no wrapping).  Going back to landscape keeps the extended text (no wrapping) until the view is reloaded (such as changing to the next day)

**Comment by mdridley** [comment]
Should be fixed in 3.0.2.1
